### ISSUE TITLE
Previous Daten unter MeterReadings werden nicht befüllt

### ISSUE THREAD

**Issue by michipi85** [DrozmotiX/ioBroker.sourceanalytix#306]
Unter dem Reiter MeterReadings werden die Daten für PreviousWeek (01_Monday; 02_Thuesday usw.) und auch die Zählerstände für 01_PrevoiusDay, 02_PreviousWeek usw. nicht befüllt.

![grafik](https://user-images.githubusercontent.com/60364178/105495835-f214f980-5cbc-11eb-8903-39fe14128305.png)

aktuelle installierter SA-Adapter 4.0.8(final) (ging jedoch bei noch keiner Version)
Node.js     v12.20.1
NPM        6.14.10
js-controller 3.1.6

**Comment by michipi85** [comment]
Kurzes Update:
Die Daten unter "previousWeek" werden doch befüllt. Jedoch nicht die DP 01_PrevoiusDay, 02_PreviousWeek usw.
![grafik](https://user-images.githubusercontent.com/60364178/106600019-25c40f00-655a-11eb-9df3-444079dd31d9.png)

**Comment by DutchmanNL** [comment]
stimmt, bin da noch dran und hatte noch kein neue version raus gehauen kommt denke ich aber vor dem WE

**Comment by DutchmanNL** [comment]
fixen in den letzten releases
