### ISSUE TITLE
Rechnungsfehler Wasserverbrauch m³ in l

### ISSUE THREAD

**Issue by m-s-b** [DrozmotiX/ioBroker.sourceanalytix#311]
Ich habe eine falsche Berechnung im Wasserverbrauch bei der Kombination m³ und Liter.
Wenn ich mit folgenden Werten starte:
Zählerstand Jahres/Quartals/Monatsbeginn 158m³ und Wochen/Tagesbeginn 160m³ ergibt das ja einen Verbrauch von 2m³ oder 2000 Litern in diesem Jahr. 
- Wenn ich den Instanzeinstellungen Wasser -> m³ auswähle errechnet er korrekt die 2m³, weitere Änderungen werden auch richtig addiert, inklusive den Kosten.
- Wenn ich in den Instanzeinstellungen Wasser ->l auswähle errechnet er mir einen falschen Verbrauch von 159.842 l und die Kosten werden mit null angegeben. Wenn ich den Zählerwert um z.B. weitere 0,01m³ erhöhe werden korrekterweise auch 10l addiert. Die Kosten bleiben aber weiterhin bei "null"

**Comment by DutchmanNL** [comment]
welche adapter version ?

**Comment by m-s-b** [comment]
0.4.8, wird mir als aktuellste angezeigt.

**Comment by DutchmanNL** [comment]
ok thanks ... was meinst du mit wasser "K" ?

**Comment by m-s-b** [comment]
sorry, meinte l (Liter). Hab es oben korrigiert.

**Comment by DutchmanNL** [comment]
ok, waehre es moeglich das du mir mal log daten zukommen lässt, wich wuerde dir dan gerne Zugang s daten schicken fuer eine SEQ monitoring server (da kan man logs hinschicken)

Mit dem adapter SEQ kannst du dan nur fuer diese adapter einmalig die Blogs schicken ich waehre sehr interessiert and deinem debug daten

**Comment by m-s-b** [comment]
Na klar, kein Problem.
Wie erstelle ich das log am besten? Das komplette vom Host runterladen?

**Comment by DutchmanNL** [comment]
> Na klar, kein Problem.
> Wie erstelle ich das log am besten? Das komplette vom Host runterladen?

am besten waehre es mit SEQ zu schicken, hast du discord oder biste im forum damit ich dir die daten dazu schicken kan ?

**Comment by DutchmanNL** [comment]
@m-s-b habe glaube keine feedback mehr bekommen daher schliesse ich das issue, bei weiteren Fragen koennen wir es gerne neu offnen

**Comment by m-s-b** [comment]
Sorry für die späte Antwort, die Benachrichtigung ging wohl irgendwie unter. 
Hatte dir die Daten via SEQ geschickt und du wolltest dich melden wenn ich noch was beisteuern kann.
Ist von meiner Seite also noch offen.
