### ISSUE TITLE
Erkennung Device Rest abschaltbar

### ISSUE THREAD

**Issue by Knallochse** [DrozmotiX/ioBroker.sourceanalytix#313]
Die Device Reset Erkennung führt bei mir leider zu vollkommen falschen Werten in Sourceanalytix.

Ich zähle meinen Wasserverbrauch mit einer Esp32 Cam per Bilderkennung.
Ich hatte es jetzt schon mehrfach, das SourceAnalytix einen Wert in "valueAtDeviceReset":
geschrieben hat. Ich denke, dass kommt eventuell davon das die Bilderkennung ab und zu einen falschen Wert erkennt (Vermutung).
Wenn jetzt wieder ein richtiger Wert erkannt wird steht im Datenpunkt unter "sourceanalytix.0.Wasserzaehler.cumulativeReading"
ein fast doppelter so hoher Wert wie real, was zu einer falschen Berechnung der Werte führt. Ich muss dann diese Werte wieder per Hand ändern.

Kann man die Erkennung eines Dervice-Reset durch SourceAnalytix abschalten machen?

**Comment by barznet** [comment]
Genau so ein Problem habe ich mit Homematic HM-ES-TX-WM. Einmal pro Woche bekomme ich werte in valueAtDeviceReset. Ich kann leider keinen Grund finden und möchte auch diese Erkennung abschalten.

**Comment by Knallochse** [comment]
Es scheinen doch einige User Probleme mit der Device-Reset Funktion zu haben.
Da dieses Issues schon seit Januar offen ist (unkommentiert),  muss man leider davon ausgehen das sich der Entwickler zurückgezogen hat.

**Comment by DutchmanNL** [comment]
> muss man leider davon ausgehen das sich der Entwickler zurückgezogen hat. Früher war dieser Adapter teil der iobroker-community-adapters Repositories.

Huh? Nein der Entwickler (ich) hat halt n bissl wenig Zeit und andere Prioritäten wen Luft da ist mache ich weiter habe aber auch noch n Par andere Adapter, Arbeit und Kinder die b bissl Aufmerksamkeit brauche 

der Wechsel war nur organisatorisch für meine Übersicht der einzige Entwickler war und bin ich hierin 😉

**Comment by Knallochse** [comment]
1. Geburtstag 🎂

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.sourceanalytix/releases/tag/v0.4.14
