### ISSUE TITLE
Invalid data received for calculation for state (0)

### ISSUE THREAD

**Issue by sebastiankemmerling** [DrozmotiX/ioBroker.sourceanalytix#314]
Hallo zusammen,

ich habe das Problem, dass sourceanalytix immer "Invalid Data" meldet, wenn der Value 0 ist (Also 0 Watt aktuelle Leistung). 

z.B. 11434) Invalid data received for calculation for state : sonoff.0.Wasserkocher.ENERGY_Power and value : _{"val":0,"ack":true,"ts":1611933846842,"q":0,"from":"system.adapter.sonoff.0","user":"system.u.._

Aufgefallen ist mir dies aber bisher nur bei Tasmota-geflashten Gosund Geräten (SP1) die über den Sonoff Adapter eingebunden wurden.

Ist das schon bekannt?

**Comment by crunchip77** [comment]
> Hallo zusammen,
> 
> Ich habe das Problem, dass Sourceanalytix immer "Ungültige Daten" meldet, wenn der Wert 0 ist (auch 0 Watt aktuelle Leistung).
> 
> zB 11434) Ungültige Daten zur Berechnung für Status erhalten: sonoff.0.Wasserkocher.ENERGY_Power und Wert: _{"val": 0, "ack": true, "ts": 1611933846842, "q": 0, "from": "system.adapter.sonoff.0", "user": "system.u .._
> 
> Aufgefallen ist mir dies aber aber nur bei Tasmota-geflashten Gosundwerden (SP1) sterben über den Sonoff Adapter gegebenunden erhalten.
> 
> Ist das schon bekannt?

Hat zwar nichts mit dem Fehler zu tun, man loggt aber  energy.powertotal(kwh) und nicht energy.power(watt)

**Comment by sebastiankemmerling** [comment]
Ah, okay. Hatte angenommen, dass man sich entscheiden kann, ob man den Verbrauch oder den den Zählerwert nehmen kann.

So erklärt das z.B. ja auch verdrahtet.info auf https://www.youtube.com/watch?v=qvEubf-3jR4 (hier dann mit seiner Solaranlage aber scheinbar gleiches / ähnliches Modul. Er nimmt auch Energy.Power und nur für seinen Hausstromzähler energy.powertotal

**Comment by crunchip77** [comment]
Wenn möglich und vorhanden, immer Gesamtverbrauch/total , Watt wäre viel zu ungenau.

**Comment by DutchmanNL** [comment]
damit koennen wir dieses issue schliessen denke ich mal :)
