### ISSUE TITLE
Tasmota total.energy reset

### ISSUE THREAD

**Issue by n3roGit** [DrozmotiX/ioBroker.sourceanalytix#318]
Moin moin,
ich schreibe mal auf deutsch, da du anscheinend auch aus DE bist :D 

Ich konnte jetzt auf Anhieb nichts zu dem Thema finden, jedoch hast du mir in der Vergangenheit ja immer sehr schnell helfen können.

Ein paar meiner Tasmota Geräte vergessen ganz gerne mal ihren Zählerstand. Meistens wenn Sie stromlos geschaltet wurden. Eigentlich ist dein Adapter ja so schlau den Wert bei Reset zu erkennen und dann neu weiter zu zählen. In der Praxis scheint das aber nicht immer zu funktionieren. Immer wieder mal habe ich plötzlich negative oder sehr hohe Werte.

Ich würde natürlich gerne zu einer Lösung beitragen. Was genau brauchst du von mir um das ggfs beheben zu können?

Beste Grüße aus Bremen

---------------------------

Moin moin,
I'll write in German, since you are apparently also from DE :D 

I could not find anything on the subject right away, but you have always been able to help me very quickly in the past.

A few of my Tasmota devices like to forget their meter reading. Mostly when you were switched off. Actually, your adapter is so smart to recognize the value at reset and then to count again. In practice, however, this does not always seem to work. Every now and then I have suddenly negative or very high values.

Of course I would like to contribute to a solution. What exactly do you need from me to fix this?

Best regards from Bremen

**Comment by crunchip77** [comment]
Dann hast du aber deine Tasmota Geräte nicht richtig konfiguiert (setOption65)

**Comment by n3roGit** [comment]
Was ist das denn? :D

**Comment by DutchmanNL** [comment]
Code technisch gibt es da nicht viel zu aendern, die logic ist simple : wen wert < bekannter wert kumuliere diesen.
Kennen gerne mal nach deinen werte schauen, aber ich wette darauf das die nicht sauber reinkommen wie auch bei @crunchip77 und ein par Testern der fall war

barbadge in = barbadge out :)

**Comment by n3roGit** [comment]
Ich bin für jede Hilfe dankbar. Ich weiß nur das manche Tasmota Kisten plötzlich auf 0 springen und dann gibbet Mruks^^

**Comment by DutchmanNL** [comment]
> Ich bin für jede Hilfe dankbar. Ich weiß nur das manche Tasmota Kisten plötzlich auf 0 springen und dann gibbet Murks^^
> 
> Wie wollen wir das mit dem gucken machen?

sorry war flange ruhig :/, ist das problem noch aktuell ?

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.sourceanalytix/releases/tag/v0.4.14
