### ISSUE TITLE
Has no existing object, since nodejs /js.controller Update

### ISSUE THREAD

**Issue by D3ltorohd** [DrozmotiX/ioBroker.sourceanalytix#327]
After update inside nodejs 12.x and update to the latest js.controller, i have some log errors in the log from this adapter.

![image](https://user-images.githubusercontent.com/2923944/107156817-cf533800-6980-11eb-8aef-738b4456726a.png)

The dp is still there.

![image](https://user-images.githubusercontent.com/2923944/107156833-ec880680-6980-11eb-85e7-fe73f5eba239.png)

Greet's

**Comment by gidhap** [comment]
Updated JS controller to 3.2.16 today....
(was already on Node.js: v12.20.1 and NPM: 6.14.10) 

Same issue here now :( . 
If I can provide any data to help fixing the issue let me know.
`

sourceanalytix.0 | 2021-02-19 18:07:03.281 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Heizung_Load.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
sourceanalytix.0 | 2021-02-19 18:07:02.393 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Netzlast_Gesamt.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:07:01.315 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Summenzähler_Grid.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:07:01.290 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Heizung_Load.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:07:01.289 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Netzlast_Gesamt.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:06:58.301 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Netzlast_Gesamt.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:06:57.621 | warn | (5123) State "sourceanalytix.0.javascript__0__Eigene_Datenpunkte__Heizung_Load.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions
sourceanalytix.0 | 2021-02-19 18:06:57.089 | warn | (5123) State "sourceanalytix.0.modbus__2__holdingRegisters__8_EV-Ladestrom.Meter_Readings.05_current_year" has no existing object, this might lead to an error in future versions

`

**Comment by DutchmanNL** [comment]
solved in latest releases
