### ISSUE TITLE
Stable-Version und manuelle Eingabe Zählerstände

### ISSUE THREAD

**Issue by Siggi0904** [DrozmotiX/ioBroker.sourceanalytix#401]
Hallo,
überall wird über diesen grandiosen Adapter berichtet.
Gern würde ich den für meine ersten Shellys mit Messfunktion Steckdosen mit Messfunktion nutzen.

Könnte die Version auch über die Stable-Repo im iobroker abrufbar sein?
Ich möchte ungern auf latest im produktiven System umschalten.
Gibt es denn große Showstopper, dass die Version nicht über iobroker abrufbar ist?

2. Frage:
Ich würde gern meine Zählerstände vom Stromzähler, Wasserzähler und Gaszähler auch in ioBroker abbilden.
Da wäre der Sourceanalytix scheinbar die richtige Anlaufstelle.
Wie wäre dafür der Ablauf? Denn man müsste dann ja auch ein Eingabedatum angeben.

Einen Unterzähler müsste man dann ja als separaten Datenpunkt errechnen lassen, oder?
Ich habe nämlich den Hauptzähler der EVU und einen Zähler für die Gästewohnung.
Ich bräuchte dann aber auch den Differenzverbrauch für den eigenen Verbrauch.

Großen Dank.

**Comment by rowdy238** [comment]
Hallo,

ich hätte den auch gerne im Stable-Repo im iobroker!
Wäre toll wenn das mal klappt ;)

Danke im Voraus!

**Comment by DutchmanNL** [comment]
ich erwarte ihn so gegen Weinachten nach stable bringen zu koennen noch par kleine Baustellen zu erledigen
