### ISSUE TITLE
 Known valueAtDeviceReset : (208466.7) > known cumulative value (0) cannot proceed

### ISSUE THREAD

**Issue by radebold** [DrozmotiX/ioBroker.sourceanalytix#406]
Hello together,

maybe any can instruct me, how to handle this. I had a small crash and now i received this errors.
What can I do ?

![image](https://user-images.githubusercontent.com/25064101/114716795-b2e2cb80-9d34-11eb-8eec-c84b3440c8aa.png)

Thanks for support
Thomas

**Comment by DutchmanNL** [comment]
hi, did yo have a look at he fax this error is explained there :)

**Comment by radebold** [comment]
> hi, did you have a look at the faq this error is explained there :)

I had a look, but I don't understood what exactly to do
