### ISSUE TITLE
Migrate custom_m.html to new JsonConfig

### ISSUE THREAD

**Issue by Apollon77** [DrozmotiX/ioBroker.sourceanalytix#411]
We were able to hold the HTML style confog pages - especially for the custom configurations  working for many years and admin versions now. With the rewrite of Admin in React we need to break this functionaliyt because it will not be possible to integrate "html snipets" that way as in the past.

Admin5 allows to specify the fields in a JSON format and all the rest is handled by the Admin itsefl. This new format is optional for the normal admin configuration dialog,but mandatory for the custom configuration!!

The JSON format is described in https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/JsonConfigComponent/SCHEMA.md and we will also having soon a JSON-Schema for it hopefully. Also Adapters like sql, influxdb, history and telegram are already migrated and could be used to see an example (see admin folder).

If you use special components (Tables or other "non standard field types) or you need support on how to best migrate special needs that are not available in the specification above please open an isue in admin and describe exactly what you need and how it should behave - or implement it in admin react and provide a PR.

You can test it yourself by using the react GUI from Admin 5.

Thank you for your support. It would be awesome if you could find time to check and implement this within the next 2 weeks. Please responde if you can not do that, then we can think about supportive options.

Please use https://github.com/ioBroker/ioBroker.admin/issues/692 for any questions!

**Comment by DutchmanNL** [comment]
Implemented stating form 0.4.9-0, requires admin >= 5.1.2! https://github.com/DrozmotiX/ioBroker.sourceanalytix/commit/2a7dae3c1c1e45dba00a960930fd50ee589923d5
