### ISSUE TITLE
Cannot load jsonConfig of sourceanalytix: Not exists

### ISSUE THREAD

**Issue by Sandmanyz** [DrozmotiX/ioBroker.sourceanalytix#453]
After opening a object this message appears: _Cannot load jsonConfig of sourceanalytix: Not exists_

[Screenshot ](http://sandmanyz.de/sourceanalytix.png)

SourceAnalytics: 0.4.8
Node.js: v12.18.4
ioBroker: v5.1.4

**Comment by MMeinhardt1** [comment]
Please install lautest V0.4.9 from GitHub in iobroker adapters over the GitHub icon.

**Comment by DutchmanNL** [comment]
Thank you @MMeinhardt1 will Release mee npm Package within the next days Admin 5 is still beta testing so yes fixed but not biggest priority ☺️

**Comment by DutchmanNL** [comment]
version 0.4.9 released
