### ISSUE TITLE
UnitAutoDetection W <-> Watt

### ISSUE THREAD

**Issue by MikeHellracer** [DrozmotiX/ioBroker.sourceanalytix#455]
Hi, 
some developpers use the value "Watt" instead "W" for the Unit of the Power state.
So, please check the Unit Value for "Watt" too.
thx

> *created by ioBroker.info*

**Comment by DutchmanNL** [comment]
hmm we use q library for that and basically unit should be always short, alway will look fat it to translate were needed

**Comment by MikeHellracer** [comment]
Ja du hast recht,
Ich habe auch den "anderen" Entwickler auch angeschrieben und um eine
Anpassung gebeten.

Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 12:57:

**Comment by DutchmanNL** [comment]
> Ich habe auch den "anderen" Entwickler auch angeschrieben und um eine

haha, na wen er es mach kan ich es mir sparen :P

**Comment by MikeHellracer** [comment]
Aber eines hätte ich noch.
Wäre es möglich den Speicherort der DP unterhalb der Devices zu
ermöglichen?
Bzw wählbar zu machen ob im Adapter oder Device. (ähnlich wie im Adapter
VirtualPower oder damals unter FHEM)
Dann wären alle Informationen konsolidiert und an einer Stelle mit Scripten
abrufbar. Auch im Hinblick der Vis.



Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 13:40:

**Comment by DutchmanNL** [comment]
> Aber eines hätte ich noch. Wäre es möglich den Speicherort der DP unterhalb der Devices zu ermöglichen? Bzw wählbar zu machen ob im Adapter oder Device. (ähnlich wie im Adapter VirtualPower oder damals unter FHEM) Dann wären alle Informationen konsolidiert und an einer Stelle mit Scripten abrufbar. Auch im Hinblick der Vis. Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 13:40:
> […](#)

Nein den das würde bedeuten das dieser Adapter im Baum eines anderen Zustände ändert das ist nicht conform ioBroker Datenbank Design und könnte früher oder später für unerwünschte Nebeneffekte sorgen

**Comment by MikeHellracer** [comment]
Da muss ich dir recht geben.
Leider macht es das mit den cryptischen Namen der Devices nicht
übersichtlicher.
Ggf. Könnte man alles über Aliasse Vereinen

Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 15:54:

**Comment by DutchmanNL** [comment]
> Ggf. Könnte man alles über Aliasse Vereinen

möglich, aber nicht als Funktion dieses Adapters 😁

**Comment by MikeHellracer** [comment]
Hi,
Ein Problem gibt es allerdings:
Die Einträge von SourceAnalytix können über den Schraubenschlüssel leider
nicht mehr entfernt werden.


Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 18:24:

**Comment by DutchmanNL** [comment]
> Hi, Ein Problem gibt es allerdings: Die Einträge von SourceAnalytix können über den Schraubenschlüssel leider nicht mehr entfernt werden. Dutchman ***@***.***> schrieb am Fr., 2. Juli 2021, 18:24:
> […](#)

Admin 4 oder 5?

**Comment by MikeHellracer** [comment]
Admin 4.2.1

Dutchman ***@***.***> schrieb am Mo., 5. Juli 2021, 07:53:
