### ISSUE TITLE
Device Reset nach restart hm-rega Adapter

### ISSUE THREAD

**Issue by barznet** [DrozmotiX/ioBroker.sourceanalytix#456]
Device Reset löst sich immer aus nach restart hm-rega Adapter (Homematic).  

```
2021-07-11 12:35:32.085  - hm-rega.0 (19301) ReGaHSS 192.168.178.20 up 
2021-07-11 12:35:32.102  - hm-rega.0 (19301) time difference local-ccu 0s 
2021-07-11 12:35:33.446  - hm-rega.0 (19301) request state values
2021-07-11 12:35:33.511  - sourceanalytix.0 (11959) Device reset detected for hm-rpc.0.MEQ0704673.1.ENERGY_COUNTER store current cumulatedReading 502.0823 as valueAtDeviceReset (previous valueAtDeviceReset : 0)
```

```
2021-07-12 14:07:38.312  - hm-rega.0 (31050) ReGaHSS 192.168.178.20 up
2021-07-12 14:07:39.316  - hm-rega.0 (31050) time difference local-ccu 0s
2021-07-12 14:07:40.177  - hm-rega.0 (31050) request state values
2021-07-12 14:07:40.405  - sourceanalytix.0 (11959) Device reset detected for hm-rpc.0.MEQ0704673.1.ENERGY_COUNTER store current cumulatedReading 1014.4443999999999 as valueAtDeviceReset (previous valueAtDeviceReset : 502.0823)
```

**Comment by intruder7777** [comment]
same here!!

**Comment by intruder7777** [comment]
ich finde dies ist die falsche Richtung. Ein device reset sollte schon erkannt werden. Ich finde es besser wenn man hier
} else if (((reading + calcValues.valueAtDeviceReset) < calcValues.cumulativeValue) && currentCath !== 'Watt') {

auf Differenz zwischen calcValues.valueAtDeviceReset und calcValues.cumulativeValue testet. Und diesen Wert konfigurierbar macht. 
Beispiel die Differnez ist größer als 1000 kWh dann device reset.

einfach nur deaktivierbar machen halte ich für verkehrt.

Grüße

PS: bei meinen Beobachtungen hat es sich immer nur um Nachkommawerte gehandelt die ihn zu einem Devicereset  veranlasst hatten

**Comment by DutchmanNL** [comment]
> einfach nur deaktivierbar machen halte ich für verkehrt.

Stimme dir zu das ist die Holzhammer Methode 😁
Die Idee mit dem Schwellenwert finde ich gut währe dan ein weer oder x% als Konfiguration wünschenswert?

**Comment by intruder7777** [comment]
ich glaube ein Wert ist ganz gut

**Comment by DutchmanNL** [comment]
<img width="1310" alt="Schermafbeelding 2022-02-23 om 21 24 06" src="https://user-images.githubusercontent.com/7318445/155402136-a3461e4c-140e-4614-8f0c-a56bea03dcbb.png">

**Comment by intruder7777** [comment]
damit ich nicht extra nachschauen muss  :-)
reading ist der aktuell gelesene Wert
ccumulativeValue ist der letzte Erfolgreich verarbeitete Wert ( im besten Fall, wenn kein Reset erfolgt ist, gleich dem letzten Zählerstand)
was ist hier valueatdevicereset?

**Comment by DutchmanNL** [comment]
> was ist hier valueatdevicereset?

der wert eines eventuell vorigen device reset.
also beispiel


Montag : 10 kwh
Dinsdag : 12 kwh
Mittwoch : 1 kwh (also reset passiert, Speicher in variable)
Donnerstage : 3 + valueatdevicereset = kumulativer wert

**Comment by intruder7777** [comment]
das klingt vernünftig und sieht so plausibel aus

**Comment by intruder7777** [comment]
es funktioniert !! Habe die Einstellungen so gelassen (aktiviert und 1)
hier die sql Aufzeichnung zum Zeitpunkt Rega restart
![image](https://user-images.githubusercontent.com/45670139/155408892-7d9cdc3e-031f-465e-b31e-82a77bca3d4a.png)

und das ist der Log

![image](https://user-images.githubusercontent.com/45670139/155408997-1a352dfe-c723-41e2-b70d-ceda4a15c9e8.png)

**Comment by DutchmanNL** [comment]
> es funktioniert !! Habe die Einstellungen so gelassen (aktiviert und 1) hier die sql Aufzeichnung zum Zeitpunkt Rega restart 

super danke fürs testen !

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.sourceanalytix/releases/tag/v0.4.14
