### ISSUE TITLE
Kein Alias möglich

### ISSUE THREAD

**Issue by Schimi1983** [DrozmotiX/ioBroker.sourceanalytix#457]
Hi,

sollte es nicht eine Möglichkeit für ein Alias geben?

![image](https://user-images.githubusercontent.com/4581474/127739908-939d2414-5d77-4953-9d75-0850e4181149.png)

Ist bei mir schon länger so... nun wird es aber unübersichtlich und ich wollte mal Aliase verteilen.
auch bei einem "neuen" Objekt, wird kein feld fürs Alias eingeblendet....

Wenn ich es direkt im "Objekt Baum" anpasse... dann ist nach einem restart des Adapters wieder der "alte Name" drin...

Oder eh ich den Wald vor lauter Bäumen nicht?

**Comment by DutchmanNL** [comment]
die alias Funktion hatte ich rausgenommen da ich den Mehrwert nicht t so gesehen habe, im moment übernimmt er den Namen immer 1:1

Wen gewünscht kan ich das gerne wieder einbauen

**Comment by Schimi1983** [comment]
Also ich fände es praktisch.....

da es bei mir zur Zeit so aussieht:

![image](https://user-images.githubusercontent.com/4581474/129583547-c92353ea-46b9-484b-8f9d-b0b2557922a3.png)

wenn es mehr wie die zwei "oberen" werden, dann müsste ich raten was, was ist....

**Comment by DutchmanNL** [comment]
> Also ich fände es praktisch.....
> 
> da es bei mir zur Zeit so aussieht:
> 
> ![image](https://user-images.githubusercontent.com/4581474/129583547-c92353ea-46b9-484b-8f9d-b0b2557922a3.png)
> 
> wenn es mehr wie die zwei "oberen" werden, dann müsste ich raten was, was ist....

Verstehe 2x power ist nicht praktisch eine ich im nächsten Update mit

**Comment by Schimi1983** [comment]
Echt super... DANKE!!!!! :-)

**Comment by DutchmanNL** [comment]
> Echt super... DANKE!!!!! :-)

done https://github.com/DrozmotiX/ioBroker.sourceanalytix/commit/1f076e61ae0967f5d18e26394553600de9fb0897
