### ISSUE TITLE
SourceAnalytix 0.4.9 in den "stable" wg. Admin 5

### ISSUE THREAD

**Issue by DcFamas** [DrozmotiX/ioBroker.sourceanalytix#458]
Hey @DutchmanNL,
es wäre, denke ich, besser wenn nun v. 0.4.9-0 im stable ist. Mir wurde in meinem ioBroker kein Update für SourceAnalytix angeboten, obwohl für Admin 5 0.4.9-0 die Voraussetzung ist, da sonst der Fehler #411 nicht behoben ist.

Danke dir und Grüße!

**Comment by DutchmanNL** [comment]
Ich finde den Adapter noch nicht fertig für stable, gibt da noch ein Par kleine Baustellen bleibt also erstmal noch in Beta

**Comment by DcFamas** [comment]
Hab mich glaube ich falsch ausgedrückt, habe wahrscheinlich das Wort stable falsch benutzt.
Sachverhalt ist wie folgt:
Mein ioBroker ist immer recht aktuell, nun wurde mir gestern Admin 5 angeboten. Vorher habe ich, wie erfordert, alle Adapter geupdatet, die irgendwie ein Update verlangt haben. SourceAnayltix blieb auf der 0.4.8. Daraufhin habe ich Admin 5 installiert und wieder alle Updates nachgezogen. SourceAnalytix weiter auf 0.4.8. Als ich nun etwas neues konfigurieren wollte, ging dies nicht, wegen deines Issues #411. Ich musste also manuell über GitHub die 0.4.9. installieren. 
Mein "Verbesserungsvorschlag" wäre nun, da ja Admin 5 offiziell angeboten wird, dass du auch direkt die Version 0.4.9. so anbietest, dass diese vor dem Admin 5 update installiert werden sollte.

**Comment by DutchmanNL** [comment]
@DcFamas hast du deine verwachtingsvol Orte auf latest oder stable ?

mich vermute stable da der Admin Update erst gestern kam und SA ist nicht im stable.
Kurz umstellen auf latest, diesen Adapter updaten und dan wieder zurück auf stable

**Comment by DutchmanNL** [comment]
ich werde mir im August mal das komplette project nochmal durchgehen lassen was noetig ist fuer stable.
Momentan sehe ich noch 3 Baustellen : 

- Reset von geraten konfigurabel machen
- Die JSON 
- Grundpreis

danach noch schauen ob es schwer wiegende bugs gibt, es wird aber mal zeit fuer stable von SA da gebe ich euch recht :)

**Comment by DcFamas** [comment]
Sorry, jetzt habe ich es erst verstanden. Ich habe das Update ja nicht bekommen, weil ich damals schon den Adapter über Github installiert hatte. Danke für deine fixe Antwort!
