### ISSUE TITLE
Negative Werte ignorieren

### ISSUE THREAD

**Issue by serpentes80** [DrozmotiX/ioBroker.sourceanalytix#459]
Hallo zusammen,

ist es möglich, bei der (Strom)Verbrauchsberechnung negative Werte zu ignorieren?

Hintergrund: 

ich habe ein Balkonkraftwerk und messe mit einem Shelly 3em den Gesamtverbrauch im Haus. Den Gesamtkanal des Shelly lasse ich von SA erfassen. Erzeugt das BKW mehr, als gerade im Haus verbraucht wird, geht der Gesamtverbrauch ins Negative --> ich speise ins Netz ein. In dem Moment zählt aber auch SA rückwärts.
Da meine Einspeisung nicht vergütet wird, verfälscht mir das aber den tatsächlichen Verbrauch.
Kann man daher negative "Verbrauchswerte" aus der Berechnung ausschließen, sodass nur die positiven Verbräuche berechnet werden?

**Comment by DutchmanNL** [comment]
Das währe ein Unkontrolliertes verhalten/Daten Manipulation des Adapter

besser richtigen Input versorgen, zb per Script den Wert in einen neuen Date Punkt schreibe und negative Werte rausfiltern es gibt use cases wo man wohl die negativer Werte haben möchte dan wird die Logic im Adapter und eventuelle Einstellungen zu komplex
