### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by MotschaM** [DrozmotiX/ioBroker.sourceanalytix#465]
Seit dem meine SD Karte kaputt gegangen ist, kann ich bis auf diesen Adapter alles nutzen. 

Nun zeigt er mir bei den Adapterkonfiguration: "File index_m.html not found" an. 
Was kann ich machen?? 

In den Objekten stehen noch die alten Werte drin.

**Comment by guergen1** [comment]
Adapter mal neu installiert? Oder einfach mal eine Upload probiert? Irgendwas scheint bei deiner Absturz-Situation kaputt gegangen zu sein.

**Comment by DutchmanNL** [comment]
Adapter neu drüber installieren oder beim Adapter Upload ausführen, am besten auch fixer laufen lassen da hat sich was zerschossen bei dir

**Comment by MotschaM** [comment]
könnt ihr mir da bisschen unter die Arme greifen? Bin darin nicht so fit.... Finde den Adapter auch nicht bei den Adaptern..... Sind dann meine Daten weg??

**Comment by DutchmanNL** [comment]
> könnt ihr mir da bisschen unter die Arme greifen? Bin darin nicht so fit.... Finde den Adapter auch nicht bei den Adaptern..... Sind dann meine Daten weg??

Er steht in deiner Instanz Übersicht aber nicht bei den Adaptern? Haste mal Screenshot bitte

**Comment by DutchmanNL** [comment]
Kein feedback, ich mach dan mal zu sollte das problem noch bestehen bitte melden
