### ISSUE TITLE
sourceanalytix nicht alias kompatibel

### ISSUE THREAD

**Issue by MiJo112** [DrozmotiX/ioBroker.sourceanalytix#470]
Hallo zusammen,

ich vermute einen Bug in sourceanalytix.
Um Mittagnacht werden bei Objekten mit sourceanalytix die Werte der read Funktion verändert.

Zu Nachstellen:
Wert eines Objektes z.B.ZRI-31000878.data.1-0-Current hat Werte in Wh: 208000
um kWh Werte zu erzeugen gibt es ein Alias z.B: OG_Rechts_wärme mit der Read Funktion:"(val/1000).toFixed(2)".
Damit wird aus 208000 -->208
sourceanalytix ist auf den Alias aktiviert. 
Um Mitternacht scheint sourceanalytix den Wert vom Alias aber direkt in das Quell-Objekt zu schreiben.
Damit hat dann der Alias nurnoch 0.28.

Dies passiert im Log bei 00:00:08.368 bis 00:00:08.432.
Warum passiert das.
BUG?
[Log.txt](https://github.com/DrozmotiX/ioBroker.sourceanalytix/files/7454653/Log.txt)

**Comment by DutchmanNL** [comment]
nein kein bug, SA schriebt das object fuer die werte das passt aber dies darf nicht einen reset des DP zur folge haben da scheint das Alias princiep nen hickup zu haben

Bitte mal alle versions nummers, SA/JS-Controller und admin + raw daten des alias objectes

**Comment by MiJo112** [comment]
Versionen: (Aktueller Stable)
Node.js: 12.22.7
NPM: 6.14.15
JS: 3.3.18
Admin: 5.1.25
sourceanalytix: 0.4.12-1
alias: 1.2.3

RAW Grundobjekt:
`{
  "type": "state",
  "common": {
    "name": "Current Energy",
    "role": "value.power.consumption",
    "type": "number",
    "read": true,
    "write": false,
    "unit": "Wh",
    "custom": {
      "history.0": {
        "enabled": true,
        "aliasId": "",
        "changesOnly": true,
        "debounce": 1000,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "maxLength": 960,
        "retention": 0
      }
    }
  },
  "native": {
    "id": ".data.1-0-Current",
    "StorageNumber": 0
  },
  "_id": "mbus.0.ZRI-31000878.data.1-0-Current",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1633090595553
}`


RAW Alias:
`{
  "type": "state",
  "common": {
    "name": "Current Energy",
    "role": "value.power.consumption",
    "type": "number",
    "unit": "kWh",
    "read": true,
    "write": false,
    "alias": {
      "id": "mbus.0.ZRI-31000878.data.1-0-Current",
      "read": "(val/1000).toFixed(2)"
    },
    "custom": {
      "sourceanalytix.0": {
        "enabled": true,
        "selectedUnit": "Detect automatically",
        "start_day": 216,
        "start_week": 208,
        "start_month": 208,
        "start_quarter": 84,
        "start_year": 0,
        "selectedPrice": "Wärme",
        "consumption": true,
        "meter_values": true,
        "valueAtDeviceReset": 0,
        "valueAtDeviceInit": null,
        "cumulativeValue": 216
      },
      "history.0": {
        "enabled": true,
        "aliasId": "",
        "changesOnly": true,
        "debounce": 1000,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "maxLength": 960,
        "retention": 0
      }
    }
  },
  "_id": "alias.0.Aktuell.Verbrauch.OG_Rechts_wärme",
  "native": {},
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1635807601443
}`

**Comment by DutchmanNL** [comment]
lasst du mal bitte den state mitloggen z.b. mit InfluxDB ? ich moechte wissen was dort passiert den SA schreibt niemals auf der. Source vermute alias

**Comment by MiJo112** [comment]
![alias](https://user-images.githubusercontent.com/35043404/139819101-bf888ff5-9814-4768-8098-b22999f8ceb7.png)
![grund_objekt](https://user-images.githubusercontent.com/35043404/139819108-620dc4b1-8243-44dc-a4cd-1b59887c4020.png)
Hier zwei Screenshots, logge schon mit.

Ich vermute der SA schreibt auf den Alias, der dann zur Source zurückschreibt.
Warum muss der SA überhaut auf das Objekt schreiben?

**Comment by DutchmanNL** [comment]
> Hier zwei Screenshots, logge schon mit.
> 
> Ich vermute der SA schreibt auf den Alias, der dann zur Source zurückschreibt. Warum muss der SA überhaut auf das Objekt schreiben?

Nein, SA schreibt nicht den wert nur das object um darin die start. werte zwischen zsm speichern.
Dein Screenshot ist unvolstaendig bitte alle werte des loggen mitgeben (auch die source)

**Comment by DutchmanNL** [comment]
hab den code nochmal analysiert, da ist noch ein workarround drin wegen DEV 0 bug aus ner alten controller Version das könnte jetzt das problem sein.

Mit Sicherheit weis ich es mit volstaendigen log

**Comment by DutchmanNL** [comment]
> Log von souceanalytics? :
> [iobroker.2021-11-01.log](https://github.com/DrozmotiX/ioBroker.sourceanalytix/files/7460120/iobroker.2021-11-01.log)

nein, vom SQL z.b. :
<img width="1589" alt="Schermafbeelding 2021-11-02 om 12 37 02" src="https://user-images.githubusercontent.com/7318445/139839352-eb501bf8-8f40-4cae-b0cc-ac62fb1d8047.png">



es geht mir um die spalte from

**Comment by MiJo112** [comment]
Ich Logge mit History.
storeFrom war nicht aktiv, habs jetzt erst aktiviert.
Habe die Werte erst Morgen früh

**Comment by DutchmanNL** [comment]
> Ich Logge mit History.
> storeFrom war nicht aktiv, habs jetzt erst aktiviert.
> Habe die Werte erst Morgen früh

Danke!

**Comment by intruder7777** [comment]
ich habe dieses Problem auch seit geraumer Zeit. Auch in Verbindung mit andauernder Erkennung mit Zählerresets.
Und sourceanalytics schreibt in die Source. Hier von meinem Wasserzähler der von dem MQTT Adapter ausgelesen wird. Ich würde den gerne auswerten mit sourceanalytics. Ist so aber nicht möglich.
![image](https://user-images.githubusercontent.com/45670139/139928990-009ab099-8150-4f8c-98a7-62e8b9d5214e.png)

**Comment by DutchmanNL** [comment]
Ich glaube dank eurer logs und Hinweise kommen wir einer der größten bugs von SA auf der Spur

hab da ne Vermutung und versuche zu reproduzieren aber logs und logging(influxDB/Sal oder ähnlich) hätte ich trotzdem gerne

**Comment by MiJo112** [comment]
Anbei der Komplette Log + Screenshot von einem anderen Objekt.
![alias](https://user-images.githubusercontent.com/35043404/140026081-e4cd58f4-4a9c-4e3e-b233-5e29c2cfa461.png)
![source](https://user-images.githubusercontent.com/35043404/140026082-194eef37-6a49-4bdb-bee4-9c1eb8aeb3b3.png)
[iobroker.2021-11-03.log](https://github.com/DrozmotiX/ioBroker.sourceanalytix/files/7466074/iobroker.2021-11-03.log)

**Comment by DutchmanNL** [comment]
> Anbei der Komplette Log + Screenshot von einem anderen Objekt.
> ![alias](https://user-images.githubusercontent.com/35043404/140026081-e4cd58f4-4a9c-4e3e-b233-5e29c2cfa461.png)
> ![source](https://user-images.githubusercontent.com/35043404/140026082-194eef37-6a49-4bdb-bee4-9c1eb8aeb3b3.png)
> [iobroker.2021-11-03.log](https://github.com/DrozmotiX/ioBroker.sourceanalytix/files/7466074/iobroker.2021-11-03.log)

danke damit hat ich meine Vermutung bestätigt und kan das verhalten reproduzieren, muss bisl überlegen wie ich das abfangen kan es wird n update geben und auch abhaengikeit das mindestens JS-controller 3.2.x noetig sein wird damit das alles saber klappt

**Comment by DutchmanNL** [comment]
Ich habe soeben 0.4.12-2 als quick-fix auf git geladen (wird nicht im admin angeboten !)
@MiJo112 @intruder7777 koenste ihr bitte mal diese version von git testen ?

**Comment by MiJo112** [comment]
Ist Installiert, ob es klappt sehen wir morgen.

**Comment by DutchmanNL** [comment]
> Ist Installiert, ob es klappt sehen wir morgen.

vielen dank, wen dieser "Quick & Dirty fix" klappt is die stelle und logic bekannt und muss ich nur noch ein paar Sachen ergänzen zur release

**Comment by intruder7777** [comment]
ist auch installiert und 4 Objekte eingerichtet. Werte werden mitgelogt

**Comment by DutchmanNL** [comment]
> ist auch installiert und 4 Objekte eingerichtet. Werte werden mitgelogt

Vielen Dank für die aktive Mitarbeiter so macht Entwicklung Spaß

**Comment by MiJo112** [comment]
Guten Morgen,

anbei wieder Screenshots + Kompletter Tageslog.
Fehler ist mit der 4.12-2 nicht mehr da.

![alias](https://user-images.githubusercontent.com/35043404/140270387-a911b1c1-f4e5-4158-a39e-6e89ec16b6a8.png)
![source](https://user-images.githubusercontent.com/35043404/140270394-e7540495-2de7-45d6-9d55-be3dd92fb527.png)
[iobroker.2021-11-04.log](https://github.com/DrozmotiX/ioBroker.sourceanalytix/files/7472842/iobroker.2021-11-04.log)

**Comment by DutchmanNL** [comment]
> Guten Morgen,
> 
> anbei wieder Screenshots + Kompletter Tageslog. Fehler ist mit der 4.12-2 nicht mehr da.

ehr gut, wir beobachten das jetzt mal 2-3 tage und Warten auch auf feedback von @intruder7777 
Sollte das dan alles passen hab ich nächste Woche was zu tun :)

**Comment by intruder7777** [comment]
da es hier auch um das Schreiben in die Source geht... Ich hatte in einem anderen Issue das Problem mit dem Neustart der HM- Adapter (REGA, RPC) geschildert. hier wird ein reset erkannt. und der Zählerstand verdoppelt sich.
Hier der Log auf der source zum Zeitpunkt der Adapterneustarts.
![image](https://user-images.githubusercontent.com/45670139/140374035-5ec839ae-5615-4333-b91f-144976504daf.png)

und hier der Log auf dem comulative reading von sourceanalytix.
![image](https://user-images.githubusercontent.com/45670139/140374353-bca3e6bf-814c-4bee-8cd3-a061f3e74732.png)


das ist so leider noch nicht nutzbar. es verfälscht die ganzen Zählerstände

**Comment by intruder7777** [comment]
okay, alles klar. dachte nur es geht allgemein um das Schreiben auf die Source.

**Comment by DutchmanNL** [comment]
0.4.12 released @intruder7777 das HM issue kommt jetzt dran
