### ISSUE TITLE
Fehlerhafter Zäherstand nach Neustart stoppt Adapter

### ISSUE THREAD

**Issue by Chaot1** [DrozmotiX/ioBroker.sourceanalytix#474]
Ich habe nach jedem Neustart des Servers auf dem der ioBroker läuft eine Fehlermeldung das scheinbar der letzte Zählerstand nicht übereinstimmt und deshalb die Berechnung gestoppt wird:
`<html>
<body>

sourceanalytix.0 | 2021-11-17 21:11:20.999 | error | Initialization of sonoff.0.Zaehler.SML_Actual_pow failed, check warn messages !
-- | -- | -- | --
sourceanalytix.0 | 2021-11-17 21:11:20.997 | error | Cannot handle calculations for sonoff.0.Zaehler.SML_Actual_pow, check log messages and adjust settings!
sourceanalytix.0 | 2021-11-17 21:11:20.996 | error | Troubleshoot Data sonoff.0.Zaehler.SML_Actual_pow custom Data : {"_id":"sonoff.0.Zaehler.SML_Actual_pow","common":{"role":"value","read":true,"write":false,"type":"number","unit":"kWh","name":"Zaehler SML Actual_pow","custom":{"sourceanalytix.0":{"enabled":true,"selectedUnit":"kWh","start_day":1302,"start_week":0,"start_month":0,"start_quarter":0,"start_year":0,"alias":"Gesamtstrom","selectedPrice":"ElectricityDay","costs":true,"consumption":true,"meter_values":true,"basicRate":true,"valueAtDeviceReset":31.784,"valueAtDeviceInit":0.764}}},"native":{},"type":"state","acl":{"object":1636,"state":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"},"from":"system.adapter.admin.0","user":"system.user.admin","ts":1635757558045}
sourceanalytix.0 | 2021-11-17 21:11:20.992 | error | Check settings for sonoff.0.Zaehler.SML_Actual_pow ! Known valueAtDeviceReset : (31.784) > known cumulative value (31.738) cannot proceed

</body>
</html>`

Welche Einstellung müssen da nachgestellt werden? Ich finde in der Dokumentation leider nichts.
Lässt sich das nicht auch automatisch erledigen? Nur ein Hinweis das die Stände nicht mehr passen sollte doch auch ausreichen.

**Comment by DutchmanNL** [comment]
https://github.com/DrozmotiX/ioBroker.sourceanalytix/releases/tag/v0.4.14
