### ISSUE TITLE
 Migrate from self defined _design/custom to system custom

### ISSUE THREAD

**Issue by foxriver76** [DrozmotiX/ioBroker.sourceanalytix#476]
Instead of defining `_design/custom` yourself in io-package json, please migrate from

```getObjectView('custom', 'state', ...```

to the usage of 

```getObjectView('system', 'custom', ...```

also remove `_design/custom` from io-package and increase the js-controller dependency to 3.3.

Thank you.

**Comment by DutchmanNL** [comment]
done, thanks ! https://github.com/DrozmotiX/ioBroker.sourceanalytix/commit/32da8c067b5c9da026543ca8b0218d816f30c569
