### ISSUE TITLE
MeterReading bei berechneten DP falsch

### ISSUE THREAD

**Issue by bastian1607** [DrozmotiX/ioBroker.sourceanalytix#482]
Hallo,

ich habe den Modbus und den Smartmeter Adapter. Daraus erhalte ich die Werte wie Produktion meiner PV Anlage, bzw. auch Verkauf meines Stroms etc. 
Aus diesen Werte errechne ich mir mit Blockly den Wert "Eigenverbrauch" und "Verbrauch". Sowohl die Werte aus dem Modbus als auch Smartmeter, die ich für die Berechnung nutze, tracke ich mit Sourceanalytics für die bessere Übersicht. 
Bei den beiden selbst berechneten DPs kommt es täglich vor, dass der gelesene Wert mindestens doppelt so hoch plötzlich gelesen wird, teilweise mehrmals täglich, sodass die MeterReading-Werte komplett falsch laufen und ich reseten muss, sodass meine Statistik, die ich eigentlich aufzeichnen will, dahin ist. 

Da ich die Werte nun auch einzeln tracke, kann ich eigentlich Probleme ausschließen bei den Adaptern. Ich habe das Blockly nun relativ idiotensicher geschrieben um alle Eventualitäten abzudecken (hoffe ich zumindest). Daher denke ich, dass es hier ein Problem bei SourceAnalytics gibt. 
Die Werte schreibe ich in kWh und SourceAnalytics ist so eingestellt, dass er den Wert automatisch nehmen soll. Bei der Einstellung Wert in kWh kommt der gleiche Fehler.

Blockly
![image](https://user-images.githubusercontent.com/79959369/148656175-25ba278e-7187-41ae-8ada-11673ed196a6.png)

**Comment by bastian1607** [comment]
Kann es sein, dass der Adapter selbst Werte in meinen DP schreibt? So scheint es in der influxDB auszusehen. Kann das das Problem auslösen?

Eigener DP
![image](https://user-images.githubusercontent.com/79959369/148924056-050b787d-9a79-4443-ae03-1f6e8093859d.png)

Normaler DP
![image](https://user-images.githubusercontent.com/79959369/148924114-6444415e-f6bf-4d80-aba0-1ebae83d9bce.png)

**Comment by DutchmanNL** [comment]
> Kann es sein, dass der Adapter selbst Werte in meinen DP schreibt? So scheint es in der influxDB auszusehen. Kann das das Problem auslösen?
> 
> Eigener DP ![image](https://user-images.githubusercontent.com/79959369/148924056-050b787d-9a79-4443-ae03-1f6e8093859d.png)
> 
> Normaler DP ![image](https://user-images.githubusercontent.com/79959369/148924114-6444415e-f6bf-4d80-aba0-1ebae83d9bce.png)

welche version verwendest du, sollte mit 0.4.12 nicht mehr passieren : 

```
0.4.12 (2021-11-15) - requires JS-Controller >= 3.2!

(DutchmanNL) Add logging to analyse error caught by sentry
(DutchmanNL) "Cannot set property 'date' of undefined" solved
(DutchmanNL) Major : New version requires JS-Controller >= 3.2!
(DutchmanNL) Add possibility to use an alternative name (alias)
(DutchmanNL) Avoid writing source state causing incorrect calculations at day reset #470
```

**Comment by DutchmanNL** [comment]
@bastian1607 ist dir bereits aufgefallen das die werte aus deinem Modus so nicht OK sind ?
Die schieten nachtben und unten, wen noester wert < vorige (siehe readme) behandeld SA die als einen zaehler reset.

Kumulierende werte koenen niemals nach hinten gehen, nur addieren was geht da schief ?

**Comment by bastian1607** [comment]
Ich habe Version 0.4.12. 
Aber: Es scheint so, als wenn der Zähler Reset mir Werte reingeschrieben hat. Was im Grunde auch Ok ist. 

Und nein, mir sind die unlogischen Werte nicht aufgefallen. Das lag wohl daran, dass Modbus jede Sekunde, aber der SmartMeter alle 5 Sekunden gelesen wird. Ein neuer Wert aus dem SmartMeter kann das Subtraktionsergebnis drücken... 

Blockly angepasst, bisher läuft es ruhig.

![image](https://user-images.githubusercontent.com/79959369/148965427-1c88082d-3a07-4a9c-8df8-182149023b26.png)


Ich melde mich morgen um noch eine Rückmeldung zu geben. Aber wie immer: Das Problem sitzt vor dem Bildschirm. Mensch, was ärgere ich mich gerade....

**Comment by bastian1607** [comment]
Sieht soweit gut aus. Solange haben die Zahlen noch nie gehalten. Ich denke, dass Ticket kann zu. Vielen Dank!

**Comment by DutchmanNL** [comment]
perfect ! :) ich markiere es auch mal als "good first issue" viele haben das problem und hier steht kurz und knackig mi den logging genau was man kontrollieren sollte also danke auch dir !
