### ISSUE TITLE
Zeit Jahreswechsel werden keine Daten mehr angelegt

### ISSUE THREAD

**Issue by DennisXK** [DrozmotiX/ioBroker.sourceanalytix#710]
Zeit der 2023 werden In SA keine Daten mehr angelegt. Woran lieget das?

<a href="https://ibb.co/dGBRJjn"><img src="https://i.ibb.co/3B1nY4t/SA.png" alt="SA" border="0"></a>

**Comment by aruttkamp** [comment]
> Adapter einmal neu starten

Jepp - Das hats gelöst. cool

**Comment by DennisXK** [comment]
Ja das hat das Problem gelöst!
