### ISSUE TITLE
richtige Einstellungen in SA

### ISSUE THREAD

**Issue by DennisXK** [DrozmotiX/ioBroker.sourceanalytix#714]
Hi, Ich werde einfach nicht schlau daraus, die richtigen Einstellungen zu finden.
Ich würde gerne meinen Stromzähler und meine PV-Anlage auswerten. Ich würde dies gerne mit den Leistungen (W) machen. Leider funktioniert das nicht, denn unter Cumulative Reading zeigt er einen falschen Zählerstand an bzw. addiert den eingegebenen Zählerstand nicht dazu (grün markiert)! Man kann auch erkennen, dass er die aktuelle Leistung bei Cumulative Reading einfach übernimmt (blau markiert ist die aktuelle Leistung des Stromzählers)

Verwende ich anstelle der Leistung (W) die Arbeit (kwh) und trage den aktuellen Zählerstand in den Einstellungen ein, funktioniert es. (rot markiert).
<a href="https://ibb.co/PC0gqWV"><img src="https://i.ibb.co/KySWTs8/bersicht.png" alt="bersicht" border="0"></a>

Einstellungen über die Leistung
<a href="https://ibb.co/XJjjNX3"><img src="https://i.ibb.co/VBJJrVQ/1.png" alt="1" border="0"></a>

Einstellung über die Arbeit
<a href="https://ibb.co/R383qqY"><img src="https://i.ibb.co/rx9xVVF/2.png" alt="2" border="0"></a>

Muss man immer um Punkt 12 Uhr den Datenpunkt in SA anlegen, um den Zählerstand unter Day eintragen zu können? Oder kann dies zu einer x-beliebigen Uhrzeit passieren?

**Comment by DutchmanNL** [comment]
Du willst einen Watt Verbrauch loggen stellst aber wh ein ? Das kan nicht funktionieren 😉

**Comment by DutchmanNL** [comment]
"Verwende ich anstelle der Leistung (W) die Arbeit (kwh) und trage den aktuellen Zählerstand in den Einstellungen ein, funktioniert es. (rot markiert)."

Dan ist doch alles richtig ?
Man sollte auch mit Arbeit und nicht Leistung rechnen wen das Gerät bereits diese Werte gibt

Nach starten des Adapter log schauen ob er Fehler ausgespuckt hat

**Comment by DennisXK** [comment]
@DutchmanNL Ja wie gesagt stelle ich (W) ein hat es das gleiche Ergebniss, der Zählerstand wird nicht dazu addiert. Es ist für mich auch unlogisch, dass ich oben "W" einstelle und unter "Startwert für den jeweiligen Zeitrum" trage ich dann kwh ein!? selbst wenn ich die kwh in wh umrechen wird der Zählerstand nicht dazu addiert.
<a href="https://ibb.co/ssG5NHV"><img src="https://i.ibb.co/xz0mBH7/bersicht1.png" alt="bersicht1" border="0"></a>
<a href="https://ibb.co/DbQKD2f"><img src="https://i.ibb.co/8B98DZg/3.png" alt="3" border="0"></a>

**Comment by DutchmanNL** [comment]
Was kommt im log?

Die Einheit oben (siehe Doku) ist immer die Einheit des Wertes selber. Die Werte unten sind die kumulativen Werte mit Watt kan man keinen Verbrauch erreichen es muss auf eh bzw kWh addiert werden

Bei wat werten fängt SA bei 0 an zu zählen sieben Einstellungen cumulatieve Reading

**Comment by DutchmanNL** [comment]
Was ich dir noch anbieten könnte währe mal gemeinsam im Discord zu treffen und mal drüber schauen ?

**Comment by DennisXK** [comment]
@DutchmanNL Ich habe es jetzt mal 3 Tage laufen lassen, zum Vergleichen.

-Meine Solaranlage wird über (W) nahezu korrekt aufgezeichnet 2wh Abweichung zu den Werten, die der Wechselrichter aufgezeichnet hat.

-Mein Stromzähler habe ich zum Test zweimal mit SA aufzeichnen lassen. Einmal mit dem (W) Wert und einmal mit dem (kwh) Wert. Hier habe ich eine Abweichung von 15-20wh zueinander. Der cumulatieve Reading Wert stimmt nach 3 Tagen exakt mit dem Stromzählerwert überein bei der Aufzeigung mit dem kwh Wert. Bei der Aufzeichnung mit dem Watt Wert vom Stromzähler geht das ja nicht. " Hast du ja oben geschrieben". Hat aber wahrscheinlich keine Einfluss auf die Auswertungen von SA?

**Comment by DutchmanNL** [comment]
Man kan Watt schon auswerten, meist ist es ungenau je nachdem wie oft der weet übertragen wird. Watt nach wh (bzw kWh) muss ja die Zeit ermitteln wirblige ein Watt weet anwesend war und wen das nicht bei jeder Änderung aktualisiert wird entsteht eine Abweichung 

Steckdosen zb übertragen gerne mit alle 10sec anstatt bei jeder Änderung
