### ISSUE TITLE
Zählerstand wurde doppelt gezählt.

### ISSUE THREAD

**Issue by New-three** [DrozmotiX/ioBroker.sourceanalytix#722]
Ich nutze Version 0.4.14.
Heute der Adapter meinen Zählerwert doppelt gezählt und demnach alle Werte durcheinander gebracht.
Kann ich den gelesen Zählerwert in der Rechnung vom Adapter Korrigieren?

**Comment by DutchmanNL** [comment]
Jep ziehe Docu (readme) Kompilationen Reading abändern
