### ISSUE TITLE
Device reset Detectet

### ISSUE THREAD

**Issue by tobiasw83** [DrozmotiX/ioBroker.sourceanalytix#753]
Hallo,

ich möchte mehrere Werte vom Shelly EM3 und homematic Stromzähler mitschreiben lassen. 

Bekomme die folgende Meldung im iobroker. 

Device reset detected for javascript.0.scriptEnabled.Messungen.HausVerbrauchShellyGemessen store current cumulatedReading 45291.44999999999 as valueAtDeviceReset (previous valueAtDeviceReset : 44162.63999999999)

Wie kann ich Den fehler eingrenzen?
Tobias

**Comment by DutchmanNL** [comment]
Empty issue without details, nothing to work on or Analyse so close ?
