### ISSUE TITLE
Neue Objekte werden ohne Attribute angelegt.

### ISSUE THREAD

**Issue by Maxtor62** [DrozmotiX/ioBroker.sourceanalytix#883]
Objekte werden ohne Attribute angelegt.
Kein "Type"
Keine "Rolle"
usw...

Installiert Version v0.4.15-alpha.0
ioBroker Admin v6.8.0

![sBug1](https://github.com/DrozmotiX/ioBroker.sourceanalytix/assets/100165416/cf9b7c4b-729c-4769-9296-8e7f1c700210)

iobroker Log:
ENERGY_Power.2023.meterReadings.weeks.34" is missing the required property "common.type"

`2023-08-25 11:30:49.014 - warn: sourceanalytix.0 (1010) Object of state "sourceanalytix.0.sonoff__0__Heizstab-Boiler__ENERGY_Power.currentYear.meterReadings.currentWeek.05_Friday" is missing the required property "common.type"
--
2023-08-25 11:30:49.030 - warn: sourceanalytix.0 (1010) Object of state "sourceanalytix.0.sonoff__0__Heizstab-Boiler__ENERGY_Power.2023.meterReadings.weeks.34" is missing the required property "common.type"`

**Comment by manny4566** [comment]
Bei mir im Log tauchen die gleichen Meldungen auf.
